name: Write current Tag to Params-File

on:
  push:
    tags:
      - '*'

jobs:
  write-version:
    runs-on: ubuntu-latest
    name: Write Version to File
    steps:
      - uses: actions/checkout@master
      - name: Update version
        uses: brettdorrans/write-version-to-file@master
        with:
          filename: '/serverVersion.params'
          placeholder: '${VERSION}'